<x-layouts.app :title="($departmentWorkspace['title'] ?? '产品中心').' · 跨境产品 ERP'">
    <div class="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
        <div>
            <p class="text-sm font-semibold text-blue-600">{{ $departmentWorkspace['eyebrow'] ?? '产品中心' }}</p>
            <h1 class="mt-1 text-3xl font-bold tracking-tight">{{ $departmentWorkspace['title'] ?? '产品项目池' }}</h1>
            <p class="mt-2 text-sm text-slate-500">{{ $departmentWorkspace['description'] ?? '统一查看项目进度、负责人和当前协作环节。' }}</p>
        </div>
        @if(! $departmentWorkspace || $departmentWorkspace['allows_create'])<a href="#create-project" class="rounded-lg bg-blue-600 px-4 py-2.5 text-center text-sm font-semibold text-white transition hover:bg-blue-700">＋ 新建产品项目</a>@endif
    </div>

    @if(! $departmentWorkspace || $departmentWorkspace['allows_create'])<details id="create-project" class="mb-6 rounded-xl border border-blue-100 bg-blue-50/50 p-5" @if ($errors->any()) open @endif>
        <summary class="cursor-pointer text-sm font-semibold text-blue-800">手动创建产品项目</summary>
        <form method="POST" action="{{ route('projects.store') }}" class="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
            @csrf
            <label class="text-sm font-medium text-slate-700">产品名称
                <input name="product_name" value="{{ old('product_name') }}" required class="mt-1.5 w-full rounded-lg border-slate-300 text-sm shadow-sm focus:border-blue-500 focus:ring-blue-500">
                @error('product_name') <span class="mt-1 block text-xs text-red-600">{{ $message }}</span> @enderror
            </label>
            <label class="text-sm font-medium text-slate-700">产品类目
                <input name="category" value="{{ old('category') }}" class="mt-1.5 w-full rounded-lg border-slate-300 text-sm shadow-sm focus:border-blue-500 focus:ring-blue-500">
            </label>
            <label class="text-sm font-medium text-slate-700">目标市场
                <input name="market" value="{{ old('market', 'US') }}" required class="mt-1.5 w-full rounded-lg border-slate-300 text-sm shadow-sm focus:border-blue-500 focus:ring-blue-500">
            </label>
            <label class="text-sm font-medium text-slate-700">优先级
                <select name="priority" class="mt-1.5 w-full rounded-lg border-slate-300 text-sm shadow-sm focus:border-blue-500 focus:ring-blue-500">
                    <option value="high" @selected(old('priority') === 'high')>高</option>
                    <option value="medium" @selected(old('priority', 'medium') === 'medium')>中</option>
                    <option value="low" @selected(old('priority') === 'low')>低</option>
                </select>
            </label>
            <div class="md:col-span-2 xl:col-span-4">
                <button type="submit" class="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-slate-800">创建并开始选品研究</button>
            </div>
        </form>
    </details>@endif

    <form method="GET" class="mb-4 grid gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-2 lg:grid-cols-5">
        <input name="search" value="{{ $filters['search'] ?? '' }}" placeholder="搜索产品名称或项目编号" class="rounded-lg border-slate-300 text-sm shadow-sm focus:border-blue-500 focus:ring-blue-500 lg:col-span-2">
        <select name="stage" class="rounded-lg border-slate-300 text-sm shadow-sm focus:border-blue-500 focus:ring-blue-500"><option value="">全部环节</option><option value="market_research" @selected(($filters['stage'] ?? '') === 'market_research')>市场研究</option><option value="website_operations" @selected(($filters['stage'] ?? '') === 'website_operations')>网站运营</option><option value="content_creative" @selected(($filters['stage'] ?? '') === 'content_creative')>内容创意</option><option value="traffic_growth" @selected(($filters['stage'] ?? '') === 'traffic_growth')>流量增长</option></select>
        <select name="priority" class="rounded-lg border-slate-300 text-sm shadow-sm focus:border-blue-500 focus:ring-blue-500"><option value="">全部优先级</option><option value="high" @selected(($filters['priority'] ?? '') === 'high')>高</option><option value="medium" @selected(($filters['priority'] ?? '') === 'medium')>中</option><option value="low" @selected(($filters['priority'] ?? '') === 'low')>低</option></select>
        <button class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">筛选项目</button>
    </form>

    <section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
        <div class="border-b border-slate-100 px-5 py-4 text-sm font-semibold text-slate-700">{{ $departmentWorkspace['list_label'] ?? '全部项目' }}</div>
        <div class="divide-y divide-slate-100">
            @forelse ($projects as $project)
                <a href="{{ route('projects.index', ['stage' => $filters['stage'] ?? null, 'project' => $project]) }}" class="flex items-center justify-between gap-4 px-5 py-4 transition hover:bg-slate-50">
                    <div>
                        <p class="font-semibold">{{ $project->product_name }}</p>
                        <p class="mt-1 text-xs text-slate-500">{{ $project->project_code }} · {{ $project->market }} · {{ $project->category ?: '未分类' }}</p>
                    </div>
                    <x-status-badge :status="$project->status" />
                </a>
            @empty
                <div class="px-5 py-14 text-center text-sm text-slate-500">{{ $departmentWorkspace ? '当前没有待处理项目。项目推进到本部门后会显示在这里。' : '还没有产品项目。请从市场研究部创建第一个选品项目。' }}</div>
            @endforelse
        </div>
    </section>

    @if($departmentWorkspace && $selectedProject)
        @php($focus = ['market_research' => ['市场研究部重点工作', '选品证据与内部 SKU'], 'website_operations' => ['网站运营部重点工作', '1688 货源、网站产品 SKU 与 Shopify'], 'content_creative' => ['内容创意部重点工作', '素材制作与上传'], 'traffic_growth' => ['流量增长部重点工作', '广告投放与数据复盘']][$filters['stage']] ?? null)
        <section class="mt-6 rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
            <div class="flex flex-col justify-between gap-3 border-b border-slate-100 pb-5 sm:flex-row sm:items-end"><div><p class="text-xs font-semibold text-blue-600">{{ $selectedProject->project_code }}</p><h2 class="mt-1 text-2xl font-bold text-slate-900">{{ $selectedProject->product_name }}</h2><p class="mt-1 text-sm text-slate-500">{{ $selectedProject->market }} · {{ $selectedProject->category ?: '未分类' }} · 负责人：{{ $selectedProject->owner?->name }}</p></div><x-status-badge :status="$selectedProject->status" /></div>
            <div class="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.45fr)_minmax(280px,0.55fr)]"><div class="rounded-xl border border-blue-100 bg-blue-50/50 p-5"><p class="text-sm font-semibold text-blue-900">{{ $focus[0] }}</p><h3 class="mt-2 text-lg font-bold text-slate-900">{{ $focus[1] }}</h3>
                @if(($filters['stage'] ?? '') === 'market_research')<div class="mt-4 grid gap-4 lg:grid-cols-2"><div><p class="text-sm font-semibold">已有选品证据</p><div class="mt-2 space-y-2">@forelse($selectedProject->researchSources as $source)<a href="{{ $source->url }}" class="block rounded-lg bg-white p-3 text-sm text-blue-700">{{ $source->custom_source_name ?: $source->platform }} · {{ $source->evidence_note ?: '查看来源' }}</a>@empty<p class="text-sm text-slate-500">暂无选品证据。</p>@endforelse</div></div><div><p class="text-sm font-semibold">内部 SKU</p><div class="mt-2 space-y-2">@forelse($selectedProject->skus as $sku)<p class="rounded-lg bg-white p-3 text-sm">{{ $sku->sku_code }} · {{ $sku->variant_name }}</p>@empty<p class="text-sm text-slate-500">尚未回填内部 SKU。</p>@endforelse</div></div></div><div class="mt-4 grid gap-3 lg:grid-cols-2"><form method="POST" action="{{ route('projects.research-sources.store', $selectedProject) }}" class="space-y-2 rounded-lg border border-blue-200 bg-white p-3">@csrf<select name="platform" class="w-full rounded border-slate-300 text-sm"><option value="tiktok">TikTok</option><option value="facebook_ads">Facebook 广告库</option><option value="amazon">Amazon</option><option value="independent_store">独立站</option><option value="other">其他</option></select><input name="custom_source_name" placeholder="其他来源名称" class="w-full rounded border-slate-300 text-sm"><input name="url" required placeholder="证据链接" class="w-full rounded border-slate-300 text-sm"><textarea name="evidence_note" placeholder="选品理由" class="w-full rounded border-slate-300 text-sm"></textarea><button class="rounded bg-blue-600 px-3 py-2 text-sm font-semibold text-white">添加选品证据</button></form><form method="POST" action="{{ route('projects.skus.store', $selectedProject) }}" class="space-y-2 rounded-lg border border-blue-200 bg-white p-3">@csrf<input name="sku_code" required placeholder="公司内部 SKU" class="w-full rounded border-slate-300 text-sm"><input name="variant_name" required placeholder="SKU 规格" class="w-full rounded border-slate-300 text-sm"><button class="rounded bg-blue-600 px-3 py-2 text-sm font-semibold text-white">回填内部 SKU</button></form></div>
                @elseif(($filters['stage'] ?? '') === 'website_operations')<div class="mt-4 grid gap-4 lg:grid-cols-3"><div><p class="text-sm font-semibold">货源、SKU 与 Shopify 产品</p><p class="mt-2 text-sm text-slate-600">1688 货源 {{ $selectedProject->sources->count() }} 条 · 已开 SKU {{ $selectedProject->skus->count() }} 个 · Shopify 页面 {{ $selectedProject->landingPages->count() }} 个。</p></div><div><p class="text-sm font-semibold">页面关联 SKU</p><p class="mt-2 text-sm text-slate-600">优先处理市场研究部已开 SKU，并确认上架组合。</p></div><div><p class="text-sm font-semibold">来自市场研究的协作</p><p class="mt-2 text-sm text-slate-600">{{ $selectedProject->decisions->where('requested_from_stage', 'website_operations')->count() }} 条 SKU 需求待处理。</p></div></div><div class="mt-4 grid gap-3 lg:grid-cols-2"><form method="POST" action="{{ route('projects.sources.store', $selectedProject) }}" class="space-y-2 rounded-lg border border-blue-200 bg-white p-3">@csrf<input name="supplier_url" required placeholder="1688 货源链接" class="w-full rounded border-slate-300 text-sm"><input name="supplier_name" placeholder="供应商名称" class="w-full rounded border-slate-300 text-sm"><input name="currency" value="CNY" required class="w-full rounded border-slate-300 text-sm"><button class="rounded bg-blue-600 px-3 py-2 text-sm font-semibold text-white">保存货源</button></form><form method="POST" action="{{ route('projects.landing-pages.store', $selectedProject) }}" class="space-y-2 rounded-lg border border-blue-200 bg-white p-3">@csrf<input name="title" value="{{ $selectedProject->product_name }}" required class="w-full rounded border-slate-300 text-sm"><input name="page_url" required placeholder="Shopify 产品链接" class="w-full rounded border-slate-300 text-sm"><input type="hidden" name="currency" value="USD"><select multiple required name="sku_ids[]" class="min-h-20 w-full rounded border-slate-300 text-sm">@foreach($selectedProject->skus as $sku)<option value="{{ $sku->id }}">{{ $sku->sku_code }} · {{ $sku->variant_name }}</option>@endforeach</select><button class="rounded bg-blue-600 px-3 py-2 text-sm font-semibold text-white">保存 Shopify 页面</button></form></div>
                @elseif(($filters['stage'] ?? '') === 'content_creative')<div class="mt-4 grid gap-4 lg:grid-cols-2"><div><p class="text-sm font-semibold">素材清单</p><p class="mt-2 text-sm text-slate-600">当前已有 {{ $selectedProject->creativeAssets->count() }} 个素材，可关联 Shopify 页面和产品 SKU。</p></div><div><p class="text-sm font-semibold">制作依据</p><p class="mt-2 text-sm text-slate-600">参考产品详情、SKU 规格与投放反馈，制作适合测试的视频素材。</p></div></div><form method="POST" enctype="multipart/form-data" action="{{ route('projects.creative-assets.store', $selectedProject) }}" class="mt-4 grid gap-2 rounded-lg border border-blue-200 bg-white p-3 md:grid-cols-2">@csrf<input name="title" required placeholder="素材名称" class="rounded border-slate-300 text-sm"><select name="asset_type" class="rounded border-slate-300 text-sm"><option value="video">视频</option><option value="image">图片</option><option value="copy">文案</option></select><select name="source_type" class="rounded border-slate-300 text-sm"><option value="original">原创</option><option value="tiktok">TikTok 参考</option><option value="amazon">Amazon 参考</option><option value="other">其他</option></select><input name="asset_file" type="file" class="text-sm"><input name="external_url" placeholder="外部素材链接" class="rounded border-slate-300 text-sm"><textarea name="copy_text" placeholder="脚本或卖点" class="rounded border-slate-300 text-sm"></textarea><div class="md:col-span-2"><button class="rounded bg-blue-600 px-3 py-2 text-sm font-semibold text-white">保存素材</button></div></form>
                @elseif(($filters['stage'] ?? '') === 'traffic_growth')<div class="mt-4 grid gap-4 lg:grid-cols-2"><div><p class="text-sm font-semibold">投放测试与反馈</p><p class="mt-2 text-sm text-slate-600">已有 {{ $selectedProject->campaignTests->count() }} 条投放记录；当前待处理反馈 {{ $selectedProject->optimizationFeedback->where('status', '!=', 'resolved')->count() }} 条。</p></div><div><p class="text-sm font-semibold">可投放资源</p><p class="mt-2 text-sm text-slate-600">视频素材 {{ $selectedProject->creativeAssets->where('asset_type', 'video')->count() }} 个 · Shopify 页面 {{ $selectedProject->landingPages->count() }} 个。</p></div></div><form method="POST" action="{{ route('projects.campaign-tests.store', $selectedProject) }}" class="mt-5 grid gap-3 rounded-lg border border-blue-200 bg-white p-4 md:grid-cols-2">@csrf<select name="platform" class="rounded-lg border-slate-300 text-sm"><option value="facebook">Facebook</option><option value="tiktok">TikTok</option></select><input name="campaign_name" required placeholder="广告系列名称" class="rounded-lg border-slate-300 text-sm"><select name="creative_asset_id" required class="rounded-lg border-slate-300 text-sm"><option value="">选择投放视频</option>@foreach($selectedProject->creativeAssets->where('asset_type', 'video') as $asset)<option value="{{ $asset->id }}">{{ $asset->title }}</option>@endforeach</select><select name="landing_page_id" required class="rounded-lg border-slate-300 text-sm"><option value="">选择 Shopify 页面</option>@foreach($selectedProject->landingPages as $page)<option value="{{ $page->id }}">{{ $page->title }}</option>@endforeach</select><input name="spend" type="number" step="0.01" min="0" required placeholder="花费（USD）" class="rounded-lg border-slate-300 text-sm"><input name="impressions" type="number" min="0" required placeholder="展示次数" class="rounded-lg border-slate-300 text-sm"><input name="clicks" type="number" min="0" required placeholder="点击次数" class="rounded-lg border-slate-300 text-sm"><input name="conversions" type="number" min="0" required placeholder="转化次数" class="rounded-lg border-slate-300 text-sm"><textarea name="feedback_note" rows="2" placeholder="投放结论或反馈" class="rounded-lg border-slate-300 text-sm md:col-span-2"></textarea><div class="md:col-span-2"><button class="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">保存投放测试</button></div></form>@endif
            </div><aside class="rounded-xl border border-slate-200 bg-white p-5"><p class="text-sm font-semibold text-slate-900">关联协作摘要</p><dl class="mt-4 space-y-3 text-sm text-slate-600"><div class="flex justify-between gap-3"><dt>详情页</dt><dd>{{ $selectedProject->landingPages->count() }} 个</dd></div><div class="flex justify-between gap-3"><dt>素材</dt><dd>{{ $selectedProject->creativeAssets->count() }} 个</dd></div><div class="flex justify-between gap-3"><dt>投放记录</dt><dd>{{ $selectedProject->campaignTests->count() }} 条</dd></div><div class="flex justify-between gap-3"><dt>待处理反馈</dt><dd>{{ $selectedProject->optimizationFeedback->where('status', '!=', 'resolved')->count() }} 条</dd></div></dl></aside></div>
        </section>
        @if(($filters['stage'] ?? '') === 'website_operations')
            <section class="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-5"><h3 class="font-semibold text-amber-900">网站产品 SKU 规格需求</h3><p class="mt-1 text-sm text-amber-800">详情页制作人填写希望上架的 SKU/套装；市场研究部收到后决定在公司内部系统开哪些 SKU。</p><form method="POST" action="{{ route('projects.decisions.store', $selectedProject) }}" class="mt-3 grid gap-3 md:grid-cols-[1fr_2fr_auto]">@csrf<input type="hidden" name="decision_type" value="sku"><input type="hidden" name="requested_from_stage" value="market_research"><input name="title" required placeholder="例如：需要 1件 / 2件 / 4件 SKU" class="rounded-lg border-amber-200 text-sm"><input name="details" required placeholder="说明页面组合、详情页展示与测试原因" class="rounded-lg border-amber-200 text-sm"><button class="rounded-lg bg-amber-600 px-4 py-2 text-sm font-semibold text-white">发送给市场研究部</button></form></section>
        @elseif(($filters['stage'] ?? '') === 'market_research')
            <section class="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-5"><h3 class="font-semibold text-amber-900">询问详情页 SKU 制作要求</h3><p class="mt-1 text-sm text-amber-800">在开内部 SKU 前，可让网站运营部明确需要哪些规格、套装或页面组合。</p><form method="POST" action="{{ route('projects.decisions.store', $selectedProject) }}" class="mt-3 grid gap-3 md:grid-cols-[1fr_2fr_auto]">@csrf<input type="hidden" name="decision_type" value="sku"><input type="hidden" name="requested_from_stage" value="website_operations"><input name="title" required placeholder="例如：请确认详情页需要的 SKU 组合" class="rounded-lg border-amber-200 text-sm"><input name="details" required placeholder="说明选品方向、准备开通的 SKU 和需要确认的问题" class="rounded-lg border-amber-200 text-sm"><button class="rounded-lg bg-amber-600 px-4 py-2 text-sm font-semibold text-white">发送给网站运营部</button></form></section>
        @endif
        @if(($filters['stage'] ?? '') === 'content_creative')
            <style>.legacy-creative-entry { display: none; }</style><section class="mt-5 rounded-xl border border-blue-200 bg-blue-50 p-5"><h3 class="font-semibold text-blue-900">上传素材</h3><p class="mt-1 text-sm text-blue-800">素材类型可多选；选择本地文件后会上传，也可仅填写外部素材链接或脚本。</p><form method="POST" enctype="multipart/form-data" action="{{ route('projects.creative-assets.store', $selectedProject) }}" class="mt-3 grid gap-3 md:grid-cols-2">@csrf<input name="title" required placeholder="素材名称" class="rounded-lg border-blue-200 text-sm"><div class="rounded-lg border border-blue-200 bg-white p-3 text-sm"><p class="font-medium">素材类型（可多选）</p><label class="mt-2 block"><input type="checkbox" name="asset_types[]" value="video"> 视频</label><label class="block"><input type="checkbox" name="asset_types[]" value="image"> 图片</label><label class="block"><input type="checkbox" name="asset_types[]" value="gif"> 动图</label><label class="block"><input type="checkbox" name="asset_types[]" value="copy"> 文案</label></div><select name="source_type" class="rounded-lg border-blue-200 text-sm"><option value="tiktok">TikTok 参考</option><option value="youtube">YouTube 参考</option><option value="other">其他</option></select><label class="rounded-lg border border-dashed border-blue-300 bg-white p-3 text-sm text-slate-600">上传文件（视频、图片或动图）<input name="asset_file" type="file" class="mt-2 block w-full"></label><input name="external_url" placeholder="外部素材链接（可选）" class="rounded-lg border-blue-200 text-sm"><textarea name="copy_text" placeholder="脚本或核心卖点（可选）" class="rounded-lg border-blue-200 text-sm"></textarea><div class="md:col-span-2"><button class="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">保存素材</button></div></form></section>
        @endif
    @endif
<style>form[action*="creative-assets"]:has(select[name="asset_type"]) { display: none; }</style>
</x-layouts.app>
