<x-layouts.app :title="$project->product_name.' · 项目协作空间'">
    <a href="{{ route('projects.index') }}" class="text-sm font-semibold text-blue-600">← 返回产品中心</a>
    <div class="mt-4 flex flex-col justify-between gap-4 border-b border-slate-200 pb-6 lg:flex-row lg:items-end"><div><p class="text-sm font-semibold text-blue-600">{{ $project->project_code }}</p><h1 class="mt-1 text-3xl font-bold">{{ $project->product_name }}</h1><p class="mt-2 text-sm text-slate-500">{{ $project->market }} · {{ $project->category ?: '未分类' }} · 负责人：{{ $project->owner?->name }}</p></div><x-status-badge :status="$project->status" /></div>
    <nav class="mt-5 flex gap-2 overflow-x-auto border-b border-slate-200 pb-3 text-sm font-semibold text-slate-600">@foreach(['overview' => '总览', 'research' => '选品调研', 'operations' => 'SKU 与页面', 'assets' => '素材', 'campaigns' => '投放', 'feedback' => '反馈'] as $key => $label)<a href="{{ route('projects.workspace', ['project' => $project, 'tab' => $key]) }}" @class(['rounded-lg px-3 py-2', 'bg-slate-900 text-white' => $tab === $key])>{{ $label }}</a>@endforeach</nav>
    @if ($tab === 'research')
        <div class="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1.25fr)_minmax(320px,0.75fr)]"><section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-sm font-semibold">选品证据与外部趋势</h2><div class="mt-4 space-y-3">@forelse($project->researchSources as $source)<div class="rounded-lg bg-slate-50 p-3"><p class="text-sm font-semibold">{{ strtoupper($source->platform) }}</p><a href="{{ $source->url }}" target="_blank" rel="noreferrer" class="mt-1 block truncate text-sm text-blue-600">{{ $source->url }}</a><p class="mt-2 text-sm text-slate-600">{{ $source->evidence_note }}</p></div>@empty<p class="text-sm text-slate-500">还没有选品证据。请录入 TikTok、Facebook 广告库、Amazon 或店铺趋势链接。</p>@endforelse</div></section><section class="rounded-xl border border-blue-100 bg-blue-50/50 p-5"><h2 class="text-sm font-semibold text-blue-900">手动添加选品证据</h2><form method="POST" action="{{ route('projects.research-sources.store', $project) }}" class="mt-4 space-y-3">@csrf<select name="platform" class="w-full rounded-lg border-slate-300 text-sm"><option value="tiktok">TikTok</option><option value="facebook_ads">Facebook 广告库</option><option value="amazon">Amazon</option><option value="shopify">Shopify</option><option value="lightanda">Lightanda</option><option value="easy">Easy</option><option value="other">其他</option></select><input name="url" type="url" required placeholder="粘贴产品、广告或趋势链接" class="w-full rounded-lg border-slate-300 text-sm"><textarea name="evidence_note" rows="4" placeholder="为什么值得继续开发：热度、竞品、视频表现、购买趋势等" class="w-full rounded-lg border-slate-300 text-sm"></textarea><button class="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">保存选品证据</button></form></section></div>
    @elseif ($tab === 'operations')
        <div class="mt-6 grid gap-6 lg:grid-cols-2"><section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-sm font-semibold">1688 货源</h2><div class="mt-4 space-y-3">@forelse($project->sources as $source)<a href="{{ $source->supplier_url }}" class="block rounded-lg bg-slate-50 p-3 text-sm text-blue-600" target="_blank" rel="noreferrer">{{ $source->supplier_url }}</a>@empty<p class="text-sm text-slate-500">尚未录入货源。</p>@endforelse</div></section><section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-sm font-semibold">SKU 与落地页</h2><div class="mt-4 space-y-3">@forelse($project->skus as $sku)<div class="rounded-lg bg-slate-50 p-3"><p class="font-medium">{{ $sku->sku_code }}</p><p class="mt-1 text-xs text-slate-500">{{ $sku->variant_name }} · {{ $sku->sku_status }}</p></div>@empty<p class="text-sm text-slate-500">尚未录入 SKU。</p>@endforelse</div></section></div>
    @else
    <div class="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(320px,0.8fr)]"><section class="space-y-6"><div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-sm font-semibold">阶段推进</h2><div class="mt-4"><x-stage-rail :stage="$project->current_stage" /></div></div><div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-sm font-semibold">待确认决策</h2><div class="mt-3 space-y-3">@forelse($project->decisions as $decision)<div class="rounded-lg bg-slate-50 p-3"><p class="font-medium">{{ $decision->title }}</p><p class="mt-1 text-xs text-slate-500">{{ $decision->decision_type }} · {{ $decision->status }}</p></div>@empty<p class="text-sm text-slate-500">暂没有待确认的 SKU、价格或规格决策。</p>@endforelse</div></div></section><aside class="rounded-xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h2 class="text-sm font-semibold">最近活动</h2></div><div class="divide-y divide-slate-100">@forelse($project->activities as $activity)<div class="px-5 py-3"><p class="text-sm">{{ $activity->event }}</p><p class="mt-1 text-xs text-slate-400">{{ $activity->actor?->name }} · {{ $activity->created_at->diffForHumans() }}</p></div>@empty<p class="px-5 py-10 text-center text-sm text-slate-500">后续协作操作会自动记录在这里。</p>@endforelse</div></aside></div>
    @endif
</x-layouts.app>
